<a href="https://colab.research.google.com/github/MuskanSinhaPi/Intern/blob/main/ProcessingOGdataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
!pip install google.colab
from google.colab import drive
import pandas as pd
from datetime import datetime

#mounting drive
drive.mount('/content/drive')
# reading data
df=pd.read_csv("/content/drive/MyDrive/internship/Datasets/San Francisco Crime/SFCrime.csv")
df = df[['Date','Time','Category','X','Y']]

#Data Cleaning

# Drop rows with any missing values
df.dropna(inplace=True)

# Create a mapping dictionary for the new categories
category_mapping = {
    'ROBBERY': 'Violent Crimes',
    'VEHICLE THEFT': 'Property Crimes',
    'ARSON': 'Violent Crimes',
    'ASSAULT': 'Violent Crimes',
    'TRESPASS': 'Miscellaneous',
    'BURGLARY': 'Property Crimes',
    'LARCENY/THEFT': 'Property Crimes',
    'WARRANTS': 'Administrative and Other Offenses',
    'OTHER OFFENSES': 'Administrative and Other Offenses',
    'DRUG/NARCOTIC': 'Drug and Alcohol Related',
    'SUSPICIOUS OCC': 'Miscellaneous',
    'LIQUOR LAWS': 'Drug and Alcohol Related',
    'VANDALISM': 'Property Crimes',
    'WEAPON LAWS': 'Violent Crimes',
    'NON-CRIMINAL': 'Non-Criminal and Special Cases',
    'MISSING PERSON': 'Non-Criminal and Special Cases',
    'FRAUD': 'Property Crimes',
    'SEX OFFENSES, FORCIBLE': 'Violent Crimes',
    'SECONDARY CODES': 'Administrative and Other Offenses',
    'DISORDERLY CONDUCT': 'Public Order Crimes',
    'RECOVERED VEHICLE': 'Non-Criminal and Special Cases',
    'KIDNAPPING': 'Violent Crimes',
    'FORGERY/COUNTERFEITING': 'Property Crimes',
    'PROSTITUTION': 'Public Order Crimes',
    'DRUNKENNESS': 'Drug and Alcohol Related',
    'BAD CHECKS': 'White Collar Crimes',
    'DRIVING UNDER THE INFLUENCE': 'Drug and Alcohol Related',
    'LOITERING': 'Public Order Crimes',
    'STOLEN PROPERTY': 'Property Crimes',
    'SUICIDE': 'Non-Criminal and Special Cases',
    'BRIBERY': 'White Collar Crimes',
    'EXTORTION': 'White Collar Crimes',
    'EMBEZZLEMENT': 'Property Crimes',
    'GAMBLING': 'Public Order Crimes',
    'PORNOGRAPHY/OBSCENE MAT': 'Non-Criminal and Special Cases',
    'SEX OFFENSES, NON FORCIBLE': 'Violent Crimes',
    'TREA': 'Non-Criminal and Special Cases'
}

# Replace the original 'Category' column with the new categories
df['Category'] = df['Category'].map(category_mapping)

# Handle the missing seconds and AM/PM indicator
df['Time'] = df['Time'].apply(lambda x: x + ':00' if len(x.split(':')) == 2 else x)  # Add seconds if missing
df['Time'] = df['Time'].apply(lambda x: x + ' AM' if 'AM' not in x and 'PM' not in x else x)  # Add AM if neither AM nor PM is present

# Correct the format string to match your date format
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format='%m/%d/%Y %H:%M:%S %p', errors='coerce') # Use %H for 24-hour format, handle errors

# Identify rows with invalid datetime values
invalid_datetimes = df[df['Datetime'].isnull()]
print("Rows with invalid datetime values:")
print(invalid_datetimes)

# Convert to the desired format (for valid datetimes)
df['Datetime'] = df['Datetime'].dt.strftime('%m/%d/%Y %I:%M:%S %p') # Convert back to 12-hour format if needed

# Update the dataframe to only include relevant columns
df = df[['Datetime', 'Category', 'X', 'Y']]

# Display the DataFrame
print(df)

# Save the DataFrame to a CSV file
csv_file_path = 'SF_crime_with_am_pm.csv'
df.to_csv(csv_file_path, index=False)

print(f"CSV file saved at {csv_file_path}")

# Uncomment the following lines if you are using Google Colab to download the file
from google.colab import files
files.download(csv_file_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


<ipython-input-6-714e89ea0e88>:10: DtypeWarning: Columns (0,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/drive/MyDrive/internship/Datasets/San Francisco Crime/SFCrime.csv")


Rows with invalid datetime values:
Empty DataFrame
Columns: [Date, Time, Category, X, Y, Datetime]
Index: []
                       Datetime         Category           X          Y
0        11/22/2004 05:50:00 PM   Violent Crimes -122.420084  37.708311
1        10/18/2005 08:00:00 PM  Property Crimes -120.500000  90.000000
2        02/15/2004 02:00:00 AM  Property Crimes -120.500000  90.000000
3        02/18/2011 05:27:00 AM   Violent Crimes -122.436220  37.724377
4        11/21/2010 05:00:00 PM   Violent Crimes -122.410541  37.770913
...                         ...              ...         ...        ...
1193396  03/09/2015 05:50:00 AM  Property Crimes -122.402592  37.803222
1193397  12/28/2015 05:00:00 PM  Property Crimes -122.421097  37.784294
1193398  10/15/2015 06:32:00 PM  Property Crimes -122.407702  37.770697
1193399  10/11/2015 03:00:00 PM  Property Crimes -122.409530  37.765718
1193400  12/15/2015 05:00:00 PM  Property Crimes -122.426672  37.743699

[1193401 rows x 4 columns]

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import pickle as pkl
import pandas as pd
import numpy as np

with open("trn.pkl", "rb") as f:
    object = pkl.load(f)

# Reshape the 4D array into a 2D array
# The -1 in the reshape lets numpy infer the correct size of that dimension
reshaped_object = object.reshape(-1, object.shape[-1])

df = pd.DataFrame(reshaped_object)
df.to_csv(r'trnpkl.csv', index=False) # Avoid saving the index

In [ ]:
import pickle as pkl

with open("trn.pkl", "rb") as f:
    object = pkl.load(f)

print(object)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   ...
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   ...
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   ...
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0.]
   [0. 1. 1. 0.]
   [0. 0. 1. 0.]
   ...
   [0. 1. 0. 0.]
   [0. 0. 0. 0.]
   [1. 0. 0. 1.]]

  [[0. 1. 0. 0.]
   [0. 0. 0. 0.]
   [1. 0. 0. 0.]
   ...
   [1. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 1. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   ...
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   ...
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   ...
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   ...
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0

In [ ]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('trnpkl.csv')

# Display the first few rows of the DataFrame
print(df.head())

     0    1    2    3
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0
